### ISSUE TITLE
Bug: prettier-ignore-start -> end around class const

### ISSUE THREAD

**Issue by samsch** [prettier/plugin-php#1194] opened 2019-10-07 19:00 UTC
**@prettier/plugin-php v0.11.2**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBYwIbeLJUBhdAFtrbAAoAJe-hCYsulhxMBjKAGUYAE81VzBsCABaACYQFmgAR0F4aHsTZTs9OQUQYhEIGDS2DLYsgwBfFigKeBh0FDR4LElQNmwYMpFK3MwwQQ68EAAeAH4wajAAHUxp6Z9ZNuwAAgBBaeBppa2lgHodpchYBCRI+GV3aEj2tgLN7Z9mmCWAVQA5ABkASQBZT9EAUQAIvZ3itXtstgBeJYARgA3Hctg8cE9RAAlT4rd4gsEQvHQ6IIzAQ5HtJbvZCkZ7+FYAcX+OPB+KWAGYiSTHktvkDPs9vtS6QzQUyltC+Oz7pzQWj6QL6YyIdCAKwSrZ7A7QOCIKJnC5QSJQTAUablEDlIA)

**Input:**
```php
<?php


class A
{
    // prettier-ignore-start
    const UNLIMITEDPLAN     = 1;
    const TRIALPLAN         = 2;
    const LOWUSAGEPLAN      = 3;
    const MEDIUMUSAGEPLAN   = 4;
    const LARGEUSAGEPLAN    = 5;
    // prettier-ignore-end
}
```

**Output:**
```php
<?php

class A
{
    // prettier-ignore-start
    UNLIMITEDPLAN     = 1
    const TRIALPLAN = 2;
    const LOWUSAGEPLAN = 3;
    const MEDIUMUSAGEPLAN = 4;
    LARGEUSAGEPLAN    = 5
    // prettier-ignore-end
}

```

**Comment by evilebottnawi** [comment] 2019-10-08 10:37
Thanks for issue

**Comment by czosel** [comment] 2020-03-21 19:00
We don't support `prettier-ignore-start` and `prettier-ignore-end`, but this issue still shows a valid bug: 

Input
```php
class A
{
    // prettier-ignore
    const UNLIMITEDPLAN     = 1;
    const TRIALPLAN         = 2;
}
```
Output
```php
class A
{
    // prettier-ignore
    UNLIMITEDPLAN     = 1
    const TRIALPLAN = 2;
}
```

**Comment by czosel** [comment] 2020-07-29 13:07
I'll close this as a duplicate of #1222.

**Closed by czosel** 2020-07-29 13:07 UTC
Labels: bug, ignore, upstream
