### ISSUE TITLE
No need to enclose single calls in parenthesis

### ISSUE THREAD

**Issue by antonioribeiro** [prettier/plugin-php#1412] opened 2020-05-03 10:10 UTC
#### Versions:

```sh
├─ @prettier/plugin-php@0.14.0
│  ├─ prettier@^1.18.2
│  ├─ prettier@1.19.1
├─ prettier@2.0.5
```

#### Options

```sh
### General
trailingComma: all
printWidth: 80
tabWidth: 4
useTabs: false
singleQuote: true
requirePragma: false
insertPragma: false

### JavaScript
semi: false

### VueJS
vueIndentScriptAndStyle: true

### PHP
phpVersion: "7.4"
trailingCommaPHP: true
braceStyle: psr-2
```

**Input:**

```php
public function __call($name, $arguments)
{
    return $this->__callTransformMethod($name, $arguments) ?? $this->__callGetMethod($name, $arguments) ?? $this->__callSetMethod($name, $arguments) ?? $this->__forwardCall($name, $arguments);
}
```

#### Output

```php
public function __call($name, $arguments)
{
    return $this->__callTransformMethod($name, $arguments) ??
        ($this->__callGetMethod($name, $arguments) ??
            ($this->__callSetMethod($name, $arguments) ??
                $this->__forwardCall($name, $arguments)));
}
```

#### Would be nice to show things this way:

```php
    public function __call($name, $arguments)
    {
        return $this->__callTransformMethod($name, $arguments) ??
               $this->__callGetMethod($name, $arguments) ??
               $this->__callSetMethod($name, $arguments) ??
               $this->__forwardCall($name, $arguments);
    }
```

**Comment by czosel** [comment] 2020-05-28 07:48
I'll close this as a duplicate of #1439 :wink:

**Closed by czosel** 2020-05-28 07:48 UTC
