### ISSUE TITLE
Align arrow in arrays ?

### ISSUE THREAD

**Issue by mathieutu** [prettier/plugin-php#118] opened 2018-02-23 12:59 UTC
I took the habit of aligning all the arrows in a array. 
Phpstorm do that automatically, and I find that a lot clearer.

```diff
-        'description'  => 'description',
-        'excerpt'      => 'extrait',
-        'date'         => 'date',
-        'time'         => 'heure',
-        'available'    => 'disponible',
-        'size'         => 'taille',
-        'already_paid' => 'déjà payé',
-    ],
+        'description' => 'description',
+        'excerpt' => 'extrait',
+        'date' => 'date',
+        'time' => 'heure',
+        'available' => 'disponible',
+        'size' => 'taille',
+        'already_paid' => 'déjà payé'
+   ]
```

What do you think about that?

**Comment by evilebottnawi** [comment] 2018-02-23 13:01
@mathieutu by default no align, we should keep open issue and get community
- :+1: Add option
- :-1: Don't add option

**Comment by nicoder** [comment] 2018-02-23 13:02
in my team we agreed not to align, one advantage is that there is less noise in git diffs.

**Comment by evilebottnawi** [comment] 2018-02-23 13:05
@nicoder thanks for response, feel free to write you opinion, just don't forget vote

**Comment by mathieutu** [comment] 2018-02-23 13:28
Adding an option don't force you to use it! 😉

**Comment by nicoder** [comment] 2018-02-23 13:32
sure, I did not see you mentioning an option at the beginning, then @evilebottnawi chimed in :)

**Comment by czosel** [comment] 2018-02-23 15:23
Please also see #120 :smile:

**Comment by czosel** [comment] 2018-02-25 15:34
I'd suggest we follow the advice here https://github.com/prettier/plugin-php/issues/120#issuecomment-368058086 and not implement alignment.

**Comment by czosel** [comment] 2018-02-26 17:40
Closing since there seems to be concensus :smile:

**Comment by evilebottnawi** [comment] 2018-02-26 17:43
@czosel very early to close, WordPress is very big community without this option they can't adapt prettier

**Comment by evilebottnawi** [comment] 2018-02-26 17:43
php != js

**Comment by czosel** [comment] 2018-02-26 17:45
I don't think that this should be a blocker for any given codebase. But we can leave the issue open if you like!

**Comment by evilebottnawi** [comment] 2018-02-26 17:47
@czosel let's leave open :+1:

**Comment by mathieutu** [comment] 2018-02-26 17:55
I think I'll still use prettier without that, but I will stay very sad..  😢

😇

**Comment by evilebottnawi** [comment] 2018-02-26 17:57
@mathieutu After stable release we will consider an option, you can help us by applying the prettier on your code base and create issue about problems :+1:

**Comment by mathieutu** [comment] 2018-02-26 21:46
@evilebottnawi Yeah I'm actually doing it, and already opened several issues.

**Comment by cmancone** [comment] 2018-03-30 12:52
As someone who has *always* aligned my arrows and everything else as well, I'd vote no on this one, and probably even no on providing an option for it.  I love my aligned arrows but the problem is that I've found that even *how* to align things causes disagreement among developers.  As a relevant example, we have a large number of definitions of multi-dimensional arrays.  I understand this is not the norm, but I'm sure we're not the only ones who run into this.  How do you line up something like this (actual code snippet from our code base)?

```php
        return [
            'status_id'     => [
                'class'         => 'status',
                'parent_class'  => status::class,
            ],
            'created_by_id' => [
                'class'         => 'created_by_membership',
            ],
            'customer_id'   => [
                'class'         => 'belongs_to',
                'parent_class'  => customer::class,
                'multi_tenant'  => true,
            ],
            'job_id'        => [
                'class'         => 'belongs_to',
                'parent_class'  => job::class,
                'multi_tenant'  => true,
            ],
            'total'         => [
                'class'         => 'price',
                'editable'      => false,
            ],
            'total_man_minutes' => [
                'class'         => 'integer',
            ],
            'fully_quoted'  => [
                'class'         => 'yes_no',
                'editable'      => false,
            ],
            'vendor_approved' => [
                'class'         => 'yes_no',
                'editable'      => false,
            ],
            'created'       => [
                'class'         => 'created',
            ],
            'updated'       => [
                'class'         => 'updated',
            ],
            'tasks'         => [
                'class'         => 'has_many_writeable',
                'child_class'   => estimate_task::class,
            ],
        ]
```
For which I see two problems: the "business" question of "What does it mean to line up nested data structures?" and then the code to actually do that.  I'm sure it isn't an impossible problem, but especially at this phase of the process I don't think it should be a high priority.  It wouldn't surprise me if you ended up with a couple options (even prettier has one or two), and this might be a good one to choose, but it is definitely a less is more sort of situation, and I'm okay with not having any options at all at the beginning.

**Comment by mathieutu** [comment] 2018-09-11 17:01
I'm closing this, as you all convinced me 😋...

And some reading to take away about that: http://mnapoli.fr/approaching-coding-style-rationally/

**Comment by mathieutu** [comment] 2018-09-11 17:10
or we can leave it open for later and other users, if you want @evilebottnawi..

**Comment by evilebottnawi** [comment] 2018-09-11 17:21
@mathieutu let's left open

**Comment by czosel** [comment] 2018-12-01 09:07
Closing due to inactivity.

**Closed by czosel** 2018-12-01 09:07 UTC
Labels: enhancement, needs investigation

**Comment by nikita-komissarov** [comment] 2023-11-27 10:43
This is the only reason why I use [phpfmt](https://github.com/kokororin/vscode-phpfmt) and not Prettier. Really looking forward to having this feature in Prettier!
