### ISSUE TITLE
Error note bug javascript when format php 

### ISSUE THREAD

**Issue by thevan96** [prettier/plugin-php#1369] opened 2020-03-31 11:32 UTC
**Prettier 2.0.2**

**PHP Plugin last release**

**Input:**

```php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Genre;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return response()->json([
                'paginate' => Book::paginate(6)
            ]);
        }

        $genres = Genre::withCount('books')->get();
        $total = count(Book::all());
        return view('user.home', compact('genres', 'total'));
    }

    public function genre($id, Request $request)
    {
        $books = Genre::findOrFail($id)
            ->books()
            ->where('available_quantity', '>', '0')
            ->orderBy('created_at', 'desc')
            ->paginate(6);

        if ($request->ajax()) {
            return response()->json(['paginate' => $books]);
        }
    }

    public function search(Request $request)
    {
        $keyword = $request->input('value');

        if ($request->ajax()) {
            $books = Book::where('title', 'LIKE', "%{$keyword}%")
                ->orWhere('author', 'LIKE', "%{$keyword}%")
                ->orderBy('created_at', 'desc')
                ->paginate(6);
            return response()->json(['paginate' => $books]);
        }
    }

    public function show($id)
    {
        $book = Book::findOrFail($id);
        $genre = $book->genre;
        return view('user.bookDetail', compact('book', 'genre'));
    }

    public function carts()
    {
        return view('user.listCart');
    }
}

```

**Output:**

![image](https://user-images.githubusercontent.com/47932916/78021695-dfbc7e80-737d-11ea-9e93-f69290551657.png)

**Comment by czosel** [comment] 2020-03-31 12:05
Yes, this is because the latest release is not compatible with prettier 2.0 yet. Let's get a new release out :wink: 

Duplicate of #1359

**Closed by czosel** 2020-03-31 12:05 UTC
