### ISSUE TITLE
Enum in namespace causes error

### ISSUE THREAD

**Issue by alexkramer98** [prettier/plugin-php#1960] opened 2022-03-31 15:08 UTC
**@prettier/plugin-php v0.18.4**
[Playground link](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDaRTtrMMEEJvBAAHgB+YzAAHUwtzDYfKGwwNjiAAgBBME2NgFFMQR8Abi2tqDufE4AxdHQT4HaQdpAA)

**Input:**
```php
<?php

namespace App\Enum;

enum Foo {}
```

**Output:**
```php
Parse Error : syntax error, unexpected 'Enum' (T_ENUM) on line 3

  1 | <?php
  2 |
> 3 | namespace App\Enum;
    |              ^
  4 |
  5 | enum Foo {}
```

**Comment by czosel** [comment] 2022-03-31 19:21
Duplicate of #1942

**Closed by czosel** 2022-03-31 19:21 UTC
